#!/usr/bin/env python
# coding: utf-8


#- Exercici 1
#Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

import numpy as np
import pandas as pd

lele = np.random.randint(100, size=(23))

if lele.ndim > 1:
    print("Error, array con más de 1 dimensión")
else:
    print( pd.Series(lele).value_counts())


#- Exercici 2
#Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

import numpy as np

lol = np.random.randint(100, size=(5, 5))

print(lol)


#- Exercici 3
#Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

import numpy as np

lol = np.random.randint(100, size=(3, 5))
#a = np.array(lol)

print(lol)

print("La suma de las columnas es: ") 
print(np.sum(lol, axis=0))      

print("La suma de las filas es: ") 
print(np.sum(lol, axis=1))  
     


#- Exercici 4
#Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

import numpy as np
import pandas as pd

def correl(x,y):
    
    data = pd.DataFrame(np.random.randint(0, 10, size=(x, y)))
    print("Matriz: ")
    print(data)
    print("Correlación: ")
    return print(data.corr())

correl(5,5)